In [1]:
import numpy as np
myPythonList = [1,9,8,3]
print(myPythonList)

[1, 9, 8, 3]


In [2]:
numpy_array_from_list=np.array(myPythonList)
print(numpy_array_from_list)


[1 9 8 3]


In [3]:
a  = np.array([1,9,8,3])
print(a)

[1 9 8 3]


In [4]:
x=numpy_array_from_list + 10
print(x)

[11 19 18 13]


In [5]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


In [6]:
#### Another type
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [7]:
### 2 D
c = np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [8]:
### 3 D
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)
(2, 2, 3)
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
##Numpy zeros
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [10]:
##Numpy ones
import numpy as np
y=np.ones((1,2,3), dtype=np.int16)
print(y.shape)	
print(y)

(1, 2, 3)
[[[1 1 1]
  [1 1 1]]]


In [11]:
##Reshape function in Numpy
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
##Stacking Numpy arrays horizontally
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
print('Horizontal stacking: ',np.hstack((a,b)))

Horizontal stacking:  [1 2 3 4 5 6]


In [16]:
##Stacking numpy arrays vertically
a=np.array([1,2,3])
b=np.array([4,5,6])
print('Vertical stacking: ',np.vstack((a,b)))

Vertical stacking:  [[1 2 3]
 [4 5 6]]


In [17]:
## Generate random number from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.54664701 4.13031479 4.80814424 5.13180378 5.89654792 5.12518294
 4.7144678  5.26441539 4.86127011 4.76554048]


In [21]:
##Asarray
A = np.matrix(np.ones((4,4)))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
##asarray
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [23]:
##Arranging numpy arrays with default spacing
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#Arranging numpy arrays with different spacing values
np.arange(1, 14, 4)

array([ 1,  5,  9, 13])

In [25]:
#Linspace
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [26]:
#linspace-2
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [27]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [28]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

In [29]:
## Slice
import numpy as np
e  = np.array([(4,5,6), (7,8,9)])
print(e)

[[4 5 6]
 [7 8 9]]


In [30]:
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

First row: [4 5 6]
Second row: [7 8 9]


In [31]:
print('Second column:', e[:,1])

Second column: [5 8]


In [32]:
## Second Row, two values
print(e[1, :2])

[7 8]


In [33]:
#Second column 2 values
print(e[:2,1])

[5 8]


In [34]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[4.19392382 4.54045642 5.64681223 4.82090485 5.56574686 5.08433556
 6.4695898  5.04449362 5.75683278 4.90225473]


In [35]:
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

4.193923821324718
6.469589804677266
5.202535068300591
5.064414590379927
0.6302683213675803


In [36]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

In [37]:
### Matmul: matrix product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [38]:
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [39]:
# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


In [40]:
# Let's create a square matrix (NxN matrix)
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

3

In [41]:
##Eigenvectors and eigenvalues
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -2.57831463e-15  5.57979826e-17] [[-0.15115432  0.72704996  0.51747505 -0.06588506]
 [-0.34923733  0.28320876 -0.82375673 -0.31743721]
 [-0.54732033 -0.16063243  0.09508831  0.83252961]
 [-0.74540333 -0.60447363  0.21119337 -0.44920733]]


In [42]:
# make matrix with numpy
gfg = np.matrix('[6, 2; 3, 4]')
         
# applying matrix.diagonal() method
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


In [43]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


In [44]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.trace() method to find the trace of a matrix ie, the sum of principal diagonal elements of the matrix
tracem = gfg.trace()
    
print(tracem)

[[7]]
